name: 'Build'

on:
  workflow_run:
    workflows: ["Terraform"]
    types: 
      - completed

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build