name: 'Build and Publish'

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    outputs:
      bucket_url: ${{ steps.bucket.outputs.BUCKET_URL }}
      website_url: ${{ steps.website.outputs.WEBSITE_URL }}
      cloudfront_distribution_id: ${{ steps.cloudfront.outputs.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infra

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./infra
      continue-on-error: false

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infra

    - name: Set Bucket URL
      id: bucket
      run: echo "BUCKET_URL=$(terraform output -raw bucket_url)" >> "$GITHUB_OUTPUT"
      working-directory: ./infra

    - name: Set Website URL
      id: website
      run: echo "WEBSITE_URL=$(terraform output -raw website_url)" >> "$GITHUB_OUTPUT"
      working-directory: ./infra

    - name: Set CloudFront Distribution ID
      id: cloudfront
      run: echo "CLOUDFRONT_DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)" >> "$GITHUB_OUTPUT"
      working-directory: ./infra

  build:
    needs: terraform
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload dist folder
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  publish:
    needs: [terraform, build]
    name: 'Publish'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Download dist folder
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-1

    - name: Sync to S3
      env:
        AWS_S3_BUCKET: ${{ needs.terraform.outputs.bucket_url }}
      run: aws s3 sync dist/ $AWS_S3_BUCKET --delete

    - name: Invalidate CloudFront
      env:
        CLOUDFRONT_DISTRIBUTION_ID: ${{ needs.terraform.outputs.cloudfront_distribution_id }}
      run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" "/"

    - name: Echo URL
      env:
        WEBSITE_URL: ${{ needs.terraform.outputs.website_url }}
      run: echo "$WEBSITE_URL" >> "$GITHUB_STEP_SUMMARY"
